defaults:
  - _self_

server:
  _target_: dataset_server.DatasetServer

  dataset:
    _target_: dataset_server.datasets.JSONRecordDataset
    records:
      _target_: dataset_server.functional.read_jsonl
      filename: ???
